name: robustqa
channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - python=3.8
  - cudatoolkit=11.3
  - numpy
  - tqdm
  - pytorch
  - pip:
    - tqdm==4.62.3
    - transformers==4.16.2
    - tensorboard
    - tensorflow
    - tensorboardX
    - nlpaug
